version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.10.1
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlflow.db:/mlflow/mlflow.db
    environment:
      MLFLOW_SERVER_ALLOWED_HOSTS: "localhost,127.0.0.1,mlflow_server,localhost:5000,127.0.0.1:5000,mlflow_server:5000"
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/mlruns
      --host 0.0.0.0
      --port 5000
      --allowed-hosts "localhost,127.0.0.1,mlflow_server,localhost:5000,127.0.0.1:5000,mlflow_server:5000"

  postgres_checkpoint:
    image: postgres:15
    container_name: audit_checkpoints
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=checkpoints
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - audit_network

  chroma:
    image: chromadb/chroma:latest
    container_name: audit_chroma
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - audit_network

  promtheus:
    image: prom/prometheus:latest
    container_name: audit_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows Docker to see your local FastAPI
    networks:
      - audit_network


# --- CRITICAL: Declare the volumes and network ---
volumes:
  pg_data:
  chroma_data:

networks:
  audit_network:
    driver: bridge